name: Agent GUI Tests

on:
  push:
    branches: [ main, feat/agent-gui-tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Run tests
      run: |
        pytest -q --tb=short
      env:
        NOX_METRICS_ENABLED: "1"

    - name: Test API server startup
      run: |
        timeout 10s uvicorn nox_api.api.nox_api:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        curl -f http://localhost:8000/gui || exit 1
      env:
        NOX_METRICS_ENABLED: "1"